# Generated by Django 3.0.5 on 2021-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('token', models.CharField(blank=True, default='', max_length=100)),
                ('creado', models.DateField(auto_now=True)),
                ('id_Empresa', models.CharField(blank=True, default='', max_length=9)),
                ('ts', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioList',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=20)),
                ('ts', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
