# Generated by Django 3.0.5 on 2021-06-01 18:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210531_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='registroTrabajo',
            field=jsonfield.fields.JSONField(default={'horasTrabajadas': 0, 'ubicaciones': [], 'vacacionesDisponibles': 0, 'vacacionesUsadas': 0}),
        ),
    ]
